### ISSUE TITLE
为什么同样的配置本地运行没问题，docker部署完就获取不到视频

### ISSUE THREAD

**Issue by fgprodigal** [Evil0ctal/Douyin_TikTok_Download_API#391]
求助，同样的配置，一模一样的UA和Cookie值，本地直接跑项目是正常的，放到NAS上docker里就不行了，出口的ip都是一样的，完全没有头绪

**Comment by Evil0ctal** [comment]
修改docker内部的配置文件了吗

**Comment by fgprodigal** [comment]
> 修改docker内部的配置文件了吗

当然，和本地用的同一份crawlers/douyin/web/config.yaml

**Comment by fgprodigal** [comment]
```yaml
TokenManager:
  douyin:
    headers:
      Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
      Referer: https://www.douyin.com/
      Cookie: douyin.com; csrf_session_id=d11e93b52f41b948b490e4d9ee941ecf; ttwid=1%7CzYkYmwSitARpSiV8fw2CJ8vZdLLkRVRXYtcrpn72kcI%7C1705065988%7C41463fa90a80892d114057fa28601891727b0886fa05ce402955227650fc5a60; device_web_cpu_core=8; device_web_memory_size=8; n_mh=fi9IriIEgxeLgqnH5yLY8vaM0QT7-KyqDHaUSPlVzVg; __live_version__=%221.1.1.8009%22; webcast_local_quality=null; live_use_vvc=%22false%22; webcast_leading_last_show_time=1707617757412; webcast_leading_total_show_times=1; store-region=cn-xj; store-region-src=uid; __ac_nonce=06644a57a0087a4b4ab9c; __ac_signature=_02B4Z6wo00f01ESqlXwAAIDDFlW1ZKmuSixEipHAAHd1uNY1NSZg-v6arXZO8YQbxYtdMQgh7nCL-OvqAd3kd07e874Z3qG6.A7rlRxEYQksDgdJleW-UpBB9OT4X41y5gXb9y1-QSqOds38e9; dy_swidth=1920; dy_sheight=1080; s_v_web_id=verify_lw7s1j3a_rOktChOZ_fCk1_4BOM_9MBW_HBHXu2opQrFL; passport_csrf_token=3f505ef2d3260b13238294abc0481a9c; passport_csrf_token_default=3f505ef2d3260b13238294abc0481a9c; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%2C%22isForcePopClose%22%3A1%7D; bd_ticket_guard_client_web_domain=2; strategyABtestKey=%221715774846.922%22; toutiao_sso_user=16b010a7ae6cedc9930dafe091c802d9; toutiao_sso_user_ss=16b010a7ae6cedc9930dafe091c802d9; passport_auth_status=8a522de80fce6c7b48f4d877b04ef015%2C; passport_auth_status_ss=8a522de80fce6c7b48f4d877b04ef015%2C; xgplayer_user_id=271256449632; publish_badge_show_info=%220%2C0%2C0%2C1715774865854%22; _bd_ticket_crypt_doamin=2; _bd_ticket_crypt_cookie=37d5b3093ee12ed2234703eb0cf9db54; __security_server_data_status=1; FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAAgdhu4lLTUExYkKbZE7k1DLlRsR8MozEi3UxbCZdzFlM%2F1715788800000%2F0%2F0%2F1715775916928%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAAgdhu4lLTUExYkKbZE7k1DLlRsR8MozEi3UxbCZdzFlM%2F1715788800000%2F0%2F1715775316928%2F0%22; xg_device_score=7.384846883043844; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.258%7D; LOGIN_STATUS=0; sso_uid_tt=d2b8d367a0964e3697d507c7c7cc5ad1; sso_uid_tt_ss=d2b8d367a0964e3697d507c7c7cc5ad1; sid_ucp_sso_v1=1.0.0-KDBjY2MwNjhkNTExNWExZDA0MGUwMWEyNGQ1NTRlN2MyYzlkOTU3MzQKCRDc0JKyBhjvMRoCbGYiIDE2YjAxMGE3YWU2Y2VkYzk5MzBkYWZlMDkxYzgwMmQ5; ssid_ucp_sso_v1=1.0.0-KDBjY2MwNjhkNTExNWExZDA0MGUwMWEyNGQ1NTRlN2MyYzlkOTU3MzQKCRDc0JKyBhjvMRoCbGYiIDE2YjAxMGE3YWU2Y2VkYzk5MzBkYWZlMDkxYzgwMmQ5; odin_tt=b501497dad8b99d021a34d1c7b63ff160bd3b56e061f3719aeaa2ff119a70fcb; sid_guard=3df87829c9ec38d8edadb3646fd0307f%7C1715775580%7C21600%7CWed%2C+15-May-2024+18%3A19%3A40+GMT; uid_tt=fae6e95e00b0a6a8306527cd484c6c46; uid_tt_ss=fae6e95e00b0a6a8306527cd484c6c46; sid_tt=3df87829c9ec38d8edadb3646fd0307f; sessionid=3df87829c9ec38d8edadb3646fd0307f; sessionid_ss=3df87829c9ec38d8edadb3646fd0307f; sid_ucp_v1=1.0.0-KGZjYzc4NzY1MzgyNzBiNGNiNjdhZjA1NGEzYzJiMDE1N2EwYTE1MDIKCBDc0JKyBhgNGgJsZiIgM2RmODc4MjljOWVjMzhkOGVkYWRiMzY0NmZkMDMwN2Y; ssid_ucp_v1=1.0.0-KGZjYzc4NzY1MzgyNzBiNGNiNjdhZjA1NGEzYzJiMDE1N2EwYTE1MDIKCBDc0JKyBhgNGgJsZiIgM2RmODc4MjljOWVjMzhkOGVkYWRiMzY0NmZkMDMwN2Y; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A1%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A0%7D%22; download_guide=%221%2F20240515%2F0%22; pwa2=%220%7C0%7C1%7C0%22; IsDouyinActive=true; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A8%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A3.8%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A150%7D%22; home_can_add_dy_2_desktop=%221%22; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCUHBhb3JGRThkdjEyeDFydG5VRitFcU8ydll4RnFnSGhRR1pDZ0JTUlZ3T01YYkpOT0NUVmVLSjY0RnNWdDJ3QlNXRkcwTFBwNUo4V2JrdWtOLzcvelE9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ%3D%3D; msToken=qOlY0ATTfSV7_NugRe05T4H_qR9tGxqX-cteqxESy_gie4zeFGiMDJn3HA6Qw3_c4XO76F84Tix8Tp3dDu6vTuFqmH8_qEtyB7jAsFPTHlz87mTieyWyOX3CxTSVjg==

    proxies:
      http:
      https:

    msToken:
      url: https://mssdk.bytedance.com/web/report
      magic: 538969122
      version: 1
      dataType: 8
      strData: fWOdJTQR3/jwmZqBBsPO6tdNEc1jX7YTwPg0Z8CT+j3HScLFbj2Zm1XQ7/lqgSutntVKLJWaY3Hc/+vc0h+So9N1t6EqiImu5jKyUa+S4NPy6cNP0x9CUQQgb4+RRihCgsn4QyV8jivEFOsj3N5zFQbzXRyOV+9aG5B5EAnwpn8C70llsWq0zJz1VjN6y2KZiBZRyonAHE8feSGpwMDeUTllvq6BG3AQZz7RrORLWNCLEoGzM6bMovYVPRAJipuUML4Hq/568bNb5vqAo0eOFpvTZjQFgbB7f/CtAYYmnOYlvfrHKBKvb0TX6AjYrw2qmNNEer2ADJosmT5kZeBsogDui8rNiI/OOdX9PVotmcSmHOLRfw1cYXTgwHXr6cJeJveuipgwtUj2FNT4YCdZfUGGyRDz5bR5bdBuYiSRteSX12EktobsKPksdhUPGGv99SI1QRVmR0ETdWqnKWOj/7ujFZsNnfCLxNfqxQYEZEp9/U01CHhWLVrdzlrJ1v+KJH9EA4P1Wo5/2fuBFVdIz2upFqEQ11DJu8LSyD43qpTok+hFG3Moqrr81uPYiyPHnUvTFgwA/TIE11mTc/pNvYIb8IdbE4UAlsR90eYvPkI+rK9KpYN/l0s9ti9sqTth12VAw8tzCQvhKtxevJRQntU3STeZ3coz9Dg8qkvaSNFWuBDuyefZBGVSgILFdMy33//l/eTXhQpFrVc9OyxDNsG6cvdFwu7trkAENHU5eQEWkFSXBx9Ml54+fa3LvJBoacfPViyvzkJworlHcYYTG392L4q6wuMSSpYUconb+0c5mwqnnLP6MvRdm/bBTaY2Q6RfJcCxyLW0xsJMO6fgLUEjAg/dcqGxl6gDjUVRWbCcG1NAwPCfmYARTuXQYbFc8LO+r6WQTWikO9Q7Cgda78pwH07F8bgJ8zFBbWmyrghilNXENNQkyIzBqOQ1V3w0WXF9+Z3vG3aBKCjIENqAQM9qnC14WMrQkfCHosGbQyEH0n/5R2AaVTE/ye2oPQBWG1m0Gfcgs/96f6yYrsxbDcSnMvsA+okyd6GfWsdZYTIK1E97PYHlncFeOjxySjPpfy6wJc4UlArJEBZYmgveo1SZAhmXl3pJY3yJa9CmYImWkhbpwsVkSmG3g11JitJXTGLIfqKXSAhh+7jg4HTKe+5KNir8xmbBI/DF8O/+diFAlD+BQd3cV0G4mEtCiPEhOvVLKV1pE+fv7nKJh0t38wNVdbs3qHtiQNN7JhY4uWZAosMuBXSjpEtoNUndI+o0cjR8XJ8tSFnrAY8XihiRzLMfeisiZxWCvVwIP3kum9MSHXma75cdCQGFBfFRj0jPn1JildrTh2vRgwG+KeDZ33BJ2VGw9PgRkztZ2l/W5d32jc7H91FftFFhwXil6sA23mr6nNp6CcrO7rOblcm5SzXJ5MA601+WVicC/g3p6A0lAnhjsm37qP+xGT+cbCFOfjexDYEhnqz0QZm94CCSnilQ9B/HBLhWOddp9GK0SABIk5i3xAH701Xb4HCcgAulvfO5EK0RL2eN4fb+CccgZQeO1Zzo4qsMHc13UG0saMgBEH8SqYlHz2S0CVHuDY5j1MSV0nsShjM01vIynw6K0T8kmEyNjt1eRGlleJ5lvE8vonJv7rAeaVRZ06rlYaxrMT6cK3RSHd2liE50Z3ik3xezwWoaY6zBXvCzljyEmqjNFgAPU3gI+N1vi0MsFmwAwFzYqqWdk3jwRoWLp//FnawQX0g5T64CnfAe/o2e/8o5/bvz83OsAAwZoR48GZzPu7KCIN9q4GBjyrePNx5Csq2srblifmzSKwF5MP/RLYsk6mEE15jpCMKOVlHcu0zhJybNP3AKMVllF6pvn+HWvUnLXNkt0A6zsfvjAva/tbLQiiiYi6vtheasIyDz3HpODlI+BCkV6V8lkTt7m8QJ1IcgTfqjQBummyjYTSwsQji3DdNCnlKYd13ZQa545utqu837FFAzOZQhbnC3bKqeJqO2sE3m7WBUMbRWLflPRqp/PsklN+9jBPADKxKPl8g6/NZVq8fB1w68D5EJlGExdDhglo4B0aihHhb1u3+zJ2DqkxkPCGBAZ2AcuFIDzD53yS4NssoWb4HJ7YyzPaJro+tgG9TshWRBtUw8Or3m0OtQtX+rboYn3+GxvD1O8vWInrg5qxnepelRcQzmnor4rHF6ZNhAJZAf18Rjncra00HPJBugY5rD+EwnN9+mGQo43b01qBBRYEnxy9JJYuvXxNXxe47/MEPOw6qsxN+dmyIWZSuzkw8K+iBM/anE11yfU4qTFt0veCaVprK6tXaFK0ZhGXDOYJd70sjIP4UrPhatp8hqIXSJ2cwi70B+TvlDk/o19CA3bH6YxrAAVeag1P9hmNlfJ7NxK3Jp7+Ny1Vd7JHWVF+R6rSJiXXPfsXi3ZEy0klJAjI51NrDAnzNtgIQf0V8OWeEVv7F8Rsm3/GKnjdNOcDKymi9agZUgtctENWbCXGFnI40NHuVHtBRZeYAYtwfV7v6U0bP9s7uZGpkp+OETHMv3AyV0MVbZwQvarnjmct4Z3Vma+DvT+Z4VlMVnkC2x2FLt26K3SIMz+KV2XLv5ocEdPFSn1vMR7zruCWC8XqAG288biHo/soldmb/nlw8o8qlfZj4h296K3hfdFubGIUtqgsrZCrLCkkRC08Cv1ozEX/y6t2YrQepwiNmwDVk5IufStVvJMj+y2r9TcYLv7UKWXx3P6aySvM2ZHPaZhv+6Z/A/jIMBSvOizn4qG11iK7Oo6JYhxCSMJZsetjsnL4ecSIAufEmoFlAScWBh6nFArRpVLvkAZ3tej7H2lWFRXIU7x7mdBfGqU82PpM6znKMMZCpEsvHqpkSPSL+Kwz2z1f5wW7BKcKK4kNZ8iveg9VzY1NNjs91qU8DJpUnGyM04C7KNMpeilEmoOxvyelMQdi85ndOVmigVKmy5JYlODNX744sHpeqmMEK/ux3xY5O406lm7dZlyGPSMrFWbm4rzqvSEIskP43+9xVP8L84GeHE4RpOHg3qh/shx+/WnT1UhKuKpByHCpLoEo144udpzZswCYSMp58uPrlwdVF31//AacTRk8dUP3tBlnSQPa1eTpXWFCn7vIiqOTXaRL//YQK+e7ssrgSUnwhuGKJ8aqNDgdsL+haVZnV9g5Qrju643adyNixvYFEp0uxzOzVkekOMh2FYnFVIL2mJYGpZEXlAIC0zQbb54rSP89j0G7soJ2HcOkD0NmMEWj/7hUdTuMin1lRNde/qmHjwhbhqL8Z9MEO/YG3iLMgFTgSNQQhyE8AZAAKnehmzjORJfbK+qxyiJ07J843EDduzOoYt9p/YLqyTFmAgpdfK0uYrtAJ47cbl5WWhVXp5/XUxwWdL7TvQB0Xh6ir1/XBRcsVSDrR7cPE221ThmW1EPzD+SPf2L2gS0WromZqj1PhLgk92YnnR9s7/nLBXZHPKy+fDbJT16QqabFKqAl9G0blyf+R5UGX2kN+iQp4VGXEoH5lXxNNTlgRskzrW7KliQXcac20oimAHUE8Phf+rXXglpmSv4XN3eiwfXwvOaAMVjMRmRxsKitl5iZnwpcdbsC4jt16g2r/ihlKzLIYju+XZej4dNMlkftEidyNg24IVimJthXY1H15RZ8Hm7mAM/JZrsxiAVI0A49pWEiUk3cyZcBzq/vVEjHUy4r6IZnKkRvLjqsvqWE95nAGMor+F0GLHWfBCVkuI51EIOknwSB1eTvLgwgRepV4pdy9cdp6iR8TZndPVCikflXYVMlMEJ2bJ2c0Swiq57ORJW6vQwnkxtPudpFRc7tNNDzz4LKEznJxAwGi6pBR7/co2IUgRw1ijLFTHWHQJOjgc7KaduHI0C6a+BJb4Y8IWuIk2u2qCMF1HNKFAUn/J1gTcqtIJcvK5uykpfJFCYc899TmUc8LMKI9nu57m0S44Y2hPPYeW4XSakScsg8bJHMkcXk3Tbs9b4eqiD+kHUhTS2BGfsHadR3d5j8lNhBPzA5e+mE==
      User-Agent: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47

    ttwid:
      url: https://ttwid.bytedance.com/ttwid/union/register/
      data: '{"region":"cn","aid":1768,"needFid":false,"service":"www.ixigua.com","migrate_info":{"ticket":"","source":"node"},"cbUrlProtocol":"https","union":true}'
```

**Comment by Evil0ctal** [comment]
重启一下容器

**Comment by fgprodigal** [comment]
> 重启一下容器

重启过了，刚还以为是权限问题，chmod 777了也不行

**Comment by fgprodigal** [comment]
```
douyin_tiktok_download_api  | INFO:     172.25.0.1:33382 - "GET / HTTP/1.1" 200 OK
douyin_tiktok_download_api  | INFO:     connection closed
douyin_tiktok_download_api  | INFO:     ('172.25.0.1', 33384) - "WebSocket /?app=index&session=NEW" [accepted]
douyin_tiktok_download_api  | INFO:     connection open
douyin_tiktok_download_api  | INFO:     172.25.0.1:33382 - "GET / HTTP/1.1" 200 OK
douyin_tiktok_download_api  | INFO:     connection closed
douyin_tiktok_download_api  | INFO:     ('172.25.0.1', 33386) - "WebSocket /?app=index&session=NEW" [accepted]
douyin_tiktok_download_api  | INFO:     connection open
douyin_tiktok_download_api  | WARNING  第 1 次响应内容为空, 状态码: 200,                                      
douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
douyin_tiktok_download_api  | WARNING  第 2 次响应内容为空, 状态码: 200,                                      
douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
douyin_tiktok_download_api  | WARNING  第 3 次响应内容为空, 状态码: 200,                                      
douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
douyin_tiktok_download_api  | 程序出现异常，请检查错误信息。
douyin_tiktok_download_api  | ERROR    无效响应类型。响应类型: <class 'NoneType'>
```

**Comment by Ben-Huang** [comment]
> ```
> douyin_tiktok_download_api  | INFO:     172.25.0.1:33382 - "GET / HTTP/1.1" 200 OK
> douyin_tiktok_download_api  | INFO:     connection closed
> douyin_tiktok_download_api  | INFO:     ('172.25.0.1', 33384) - "WebSocket /?app=index&session=NEW" [accepted]
> douyin_tiktok_download_api  | INFO:     connection open
> douyin_tiktok_download_api  | INFO:     172.25.0.1:33382 - "GET / HTTP/1.1" 200 OK
> douyin_tiktok_download_api  | INFO:     connection closed
> douyin_tiktok_download_api  | INFO:     ('172.25.0.1', 33386) - "WebSocket /?app=index&session=NEW" [accepted]
> douyin_tiktok_download_api  | INFO:     connection open
> douyin_tiktok_download_api  | WARNING  第 1 次响应内容为空, 状态码: 200,                                      
> douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
> douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
> douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
> douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
> douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
> douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
> douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
> douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
> douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
> douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
> douyin_tiktok_download_api  | WARNING  第 2 次响应内容为空, 状态码: 200,                                      
> douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
> douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
> douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
> douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
> douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
> douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
> douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
> douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
> douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
> douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
> douyin_tiktok_download_api  | WARNING  第 3 次响应内容为空, 状态码: 200,                                      
> douyin_tiktok_download_api  |          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
> douyin_tiktok_download_api  |          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
> douyin_tiktok_download_api  |          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
> douyin_tiktok_download_api  |          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
> douyin_tiktok_download_api  |          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
> douyin_tiktok_download_api  |          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
> douyin_tiktok_download_api  |          e_memory=8&platform=PC&msToken=_GW7xWOy7213hWdQbzV7_3PbYBe3akqHVNdZGCS2
> douyin_tiktok_download_api  |          WNhFybcAY8q4-kuL3HICpf17Cwv3IUT4j4u56EcgG9cOBVCzKI4vD0k_XTdoQR19xpBnSpK
> douyin_tiktok_download_api  |          0lIozlevhOHwcsw==&aweme_id=7366840837692575017&X-Bogus=DFSzswVY9ZzANGVR
> douyin_tiktok_download_api  |          tl4FMF9WX7nL                                                           
> douyin_tiktok_download_api  | 程序出现异常，请检查错误信息。
> douyin_tiktok_download_api  | ERROR    无效响应类型。响应类型: <class 'NoneType'>
> ```

同样docker部署,同样的问题

**Comment by Smecta** [comment]
我是映射出来了，外面改完配置, restart 一下容器 就生效了

**Comment by Ben-Huang** [comment]
[docker-compose.yml](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/docker-compose.yml)
```
    volumes: # 挂载卷配置
      - ./douyin_tiktok_download_api/douyin_web/config.yaml:/crawlers/douyin/web/config.yaml
      - ./douyin_tiktok_download_api/tiktok_web/config.yaml:/crawlers/tiktok/web/config.yaml
      - ./douyin_tiktok_download_api/tiktok_app/config.yaml:/crawlers/tiktok/app/config.yaml
  ```
映射路径是错误的

**Comment by Evil0ctal** [comment]
像楼上那样手动映射一下yaml文件到你的本地的路径里。

**Comment by Evil0ctal** [comment]
我这边映射完之后修改配置文件是OK的，你们检查一下你们的docker映射吧。

**Comment by fgprodigal** [comment]
![IMG_3730](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/769910/6f5460ce-b996-4117-8a67-5271339d4439)

**Comment by zaimatest** [comment]
朋友，本地运行的时候是在docker内部署运行的还是宿主机环境运行的？

**Comment by fgprodigal** [comment]
> 朋友，本地运行的时候是在docker内部署运行的还是宿主机环境运行的？

本机python start.py

**Comment by fgprodigal** [comment]
> 群晖部署的时候是直接下一步，没有修改其他配置的吗？

```
version: "3.7"

services:
  # bot
  douyin_tiktok_download_api:
    image: evil0ctal/douyin_tiktok_download_api
    container_name: douyin_tiktok_download_api
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./douyin_web/config.yaml:/crawlers/douyin/web/config.yaml
#      - ./tiktok_web/config.yaml:/crawlers/tiktok/web/config.yaml
#      - ./tiktok_app/config.yaml:/crawlers/tiktok/app/config.yaml
    networks:
      network:
        ipv4_address: 172.25.0.2
    environment:
      TZ: Asia/Shanghai
      PUID: 1026  # 设置容器内部的用户 ID
      PGID: 100  # 设置容器内部的用户组 ID
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.80'
networks:
  network:
    ipam:
      config:
        - subnet: 172.25.0.0/24
 ```
